version: "3"
services:
  neo4j:
    build: ./neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - ./neo4j/data:/var/lib/neo4j/data
      - ./neo4j/config:/var/lib/neo4j/conf
      # - ./neo4j/import:/var/lib/neo4j/import

  api:
    build: ./api
    ports:
      - 4000:4000
    environment:
      - NEO4J_URI=bolt://localhost:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password

    links:
      - neo4j
    depends_on:
      - neo4j

    volumes:
      - ./api:/app
      - /app/node_modules
